### ISSUE TITLE
Contain scrolling

### ISSUE THREAD

**Issue by Hyperseeker** [ninest/basic-sidebar-layout#1]
It may be worth adding [`overscroll-behavior: contain`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) to the sidebar. When user has already scrolled to the extreme of the area (topmost or bottommost), scrolling usually "leaks" into the parent container. With `overscroll-behavior` – a relatively-new property – you get to control this.

In my experience, especially on touch-based devices, it may be confusing if the body of the text suddenly starts running away if I'm scrolling the navigation sidebar only. Given that your stated goal is to create a *basic* sidebar layout, that may be a nice default to adopt.

**Comment by ninest** [comment]
Sorry, I completely missed this issue.

I didn't realize the issue. I've changed the layout completely, and I'll definitely add this. Thanks for the tip!

**Comment by ninest** [comment]
Added in 8d3f932a32febc1bd03b212b7130e4025271d965

Note that in the new site layout, I haven't added support for mobile (yet). I decided to "revive" this project after a few months because I'm building a Nuxt Content theme off of it: [ninest/snowblack](https://github.com/ninest/snowblack)
